'use strict';
let SLIDES=language==='en'?SLIDES_EN:SLIDES_ET;
// Synthetic pedestrian graph: edge costs in minutes, node weights in dwellings.
// The live bridges demo has its own walking/cycling networks and scenarios.
const NODES = [
 {x:190,y:115,w:0},{x:130,y:270,w:8},{x:330,y:260,w:36},{x:350,y:450,w:12},
 {x:130,y:470,w:20},{x:350,y:625,w:24},{x:610,y:115,w:18},{x:650,y:285,w:56},
 {x:620,y:455,w:44},{x:715,y:630,w:10},{x:825,y:125,w:28},{x:835,y:300,w:32},{x:840,y:485,w:16}
];
const EDGES = [[0,1,4],[0,2,5],[1,2,5],[1,4,6],[2,3,5],[3,4,6],[3,5,5],[4,5,7],[0,6,13],[6,7,5],[6,10,5],[7,8,5],[7,11,5],[10,11,5],[8,9,5],[8,12,5],[11,12,5],[9,12,6]];
let demoState = {minutes:15, bridge:false, weighted:true};
function distances(bridge=false){
 const d=NODES.map(()=>Infinity);d[0]=0;
 const todo=new Set(NODES.map((_,i)=>i));const edges=bridge?[...EDGES,[3,8,4]]:EDGES;
 while(todo.size){let u=[...todo].reduce((a,b)=>d[a]<d[b]?a:b);todo.delete(u);for(const [a,b,c] of edges){const v=a===u?b:b===u?a:-1;if(v>=0&&todo.has(v))d[v]=Math.min(d[v],d[u]+c);}}
 return d;
}
function coverage(minutes,bridge=demoState.bridge,weighted=demoState.weighted){
 const d=distances(bridge);let yes=0,total=0;
 NODES.forEach((n,i)=>{if(i===0)return;let w=weighted?n.w:1;total+=w;if(d[i]<=minutes)yes+=w;});
 return {yes,total,pct:100*yes/total};
}
function networkGraphic(){
 const d=distances(demoState.bridge),time=demoState.minutes;
 return `<svg class="network" viewBox="0 0 990 740" role="img" aria-label="${tr("Sünteetiline tänavavõrk: kool, elumajad, jõgi ja võimalik uus sild. Roheline näitab ajapiiri sees saavutatud võrgu sõlmi.","Synthetic street network: school, homes, river and a possible new bridge. Green marks nodes reachable within the time threshold.")}"><title>${tr("Jalutusaeg mööda võrku — sünteetiline skeem","Walking time along the network \u2014 synthetic illustration")}</title><path class="river" d="M475 10 Q535 170 470 335 T505 735"/>${EDGES.map(([a,b])=>`<line class="road ${Math.max(d[a],d[b])<=time?'reachable':''}" x1="${NODES[a].x}" y1="${NODES[a].y}" x2="${NODES[b].x}" y2="${NODES[b].y}"/>`).join('')}${demoState.bridge?'<line class="road bridge" x1="350" y1="450" x2="620" y2="455"/>':''}${NODES.map((n,i)=>i===0?`<circle class="school" cx="${n.x}" cy="${n.y}" r="24"/><text x="${n.x-33}" y="${n.y-40}">${tr("Kool","School")}</text>`:`<rect class="house ${d[i]<=time?'covered':''}" x="${n.x-20}" y="${n.y-17}" width="40" height="34" rx="3"/><text class="${d[i]<=time?'node-label':''}" text-anchor="middle" x="${n.x}" y="${n.y+6}" style="font-size:15px">${n.w}</text><text text-anchor="middle" x="${n.x}" y="${n.y+43}" style="font-size:16px">${d[i]} min</text>`).join('')}<text x="370" y="91" class="legend">${tr("Olemasolev sild","Existing bridge")}</text><text x="480" y="694" class="legend">${tr("Jõgi","River")}</text><text x="60" y="724" class="legend">${tr("Skeem · arv majas = eluruumid · aeg koolini","Illustration \u00b7 number in building = dwellings \u00b7 time to school")}</text></svg>`;
}
function chartGraphic(){
 const W=850,H=440,L=76,R=28,T=28,B=64,x=t=>L+t/30*(W-L-R),y=v=>H-B-v/100*(H-T-B);
 function path(bridge){let out=`M ${x(0)} ${y(coverage(0,bridge).pct)}`;for(let t=1;t<=30;t++)out+=` H ${x(t)} V ${y(coverage(t,bridge).pct)}`;return out;}
 const c=coverage(demoState.minutes);
 return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="${tr(`Sünteetilise võrgu katvus jalutusaja funktsioonina. Valitud aeg ${demoState.minutes} minutit, katvus ${c.pct.toFixed(1)} protsenti.`,`Synthetic network coverage by walking time. Selected time ${demoState.minutes} minutes, coverage ${c.pct.toFixed(1)} percent.`)}"><title>${tr("Katvus kasvab ajapiiriga — näidisandmed","Coverage increases with the time threshold \u2014 example data")}</title>${[0,25,50,75,100].map(v=>`<line class="grid" x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}"/><text text-anchor="end" x="${L-15}" y="${y(v)+6}">${v}</text>`).join('')}${[0,5,10,15,20,25,30].map(t=>`<line class="grid" x1="${x(t)}" y1="${T}" x2="${x(t)}" y2="${H-B}"/><text text-anchor="middle" x="${x(t)}" y="${H-B+29}">${t}</text>`).join('')}<path class="curve" d="${path(false)}"/>${demoState.bridge?`<path class="curve-bridge" d="${path(true)}"/>`:''}<line class="cut" x1="${x(demoState.minutes)}" y1="${T}" x2="${x(demoState.minutes)}" y2="${H-B}"/><circle class="marker" cx="${x(demoState.minutes)}" cy="${y(c.pct)}" r="7"/><text text-anchor="middle" x="${(L+W-R)/2}" y="${H-6}">${tr("Jalutusaeg (min)","Walking time (min)")}</text><text transform="translate(21 218) rotate(-90)" text-anchor="middle">${tr("Katvus (%)","Coverage (%)")}</text></svg>`;
}
function demoControls(bridge=true){return `<div class="controls"><div class="range-row"><label for="walk-time">${tr("Jalutusaeg:","Walking time:")} <strong id="walk-value">${demoState.minutes} min</strong></label><input type="range" id="walk-time" min="5" max="30" step="1" value="${demoState.minutes}" aria-label="${tr("Jalutusaeg minutites","Walking time in minutes")}"></div>${bridge?`<label class="check-row"><input type="checkbox" id="bridge" ${demoState.bridge?'checked':''}>${tr("Lisa stsenaarium: uus sild","Add scenario: a new bridge")}</label>`:''}<label class="check-row"><input type="checkbox" id="weighted" ${demoState.weighted?'checked':''}>${tr("Kaalu hooneid eluruumide arvuga","Weight buildings by dwellings")}</label></div>`;}
function metricMarkup(){const c=coverage(demoState.minutes);return `<span class="huge em">${Math.round(c.pct)}<span class="unit">%</span></span><p class="metric-line">${c.yes} / ${c.total} ${demoState.weighted?tr('eluruumi','dwellings'):tr('elumaja','residential buildings')} ${tr('näidisvõrgus','in the example network')}</p>`;}

let current=0, notesOpen=false, toastTimer;
const $=selector=>document.querySelector(selector);
const total=SLIDES.reduce((s,x)=>s+x.minutes,0);
function startMinute(index){return SLIDES.slice(0,index).reduce((s,x)=>s+x.minutes,0);}
function slideIndex(){const m=location.hash.match(/^#slaid-(\d+)$/);return m?Math.max(0,Math.min(SLIDES.length-1,Number(m[1])-1)):0;}
function updateNotes(){const s=SLIDES[current],start=startMinute(current);$('#notes-body').innerHTML=`<div class="note-time">${start}–${start+s.minutes} min / ${total} min · ${tr("selle slaidi aeg","this slide")} ${s.minutes} min</div><h3>${esc(s.title)}</h3><ul>${s.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><p class="hint">${tr("N või Märkmed: sulge paneel enne publikule näitamist. Esinejamärkmed on samas aknas. ← → liigub slaidide vahel; Home / End avab esimese / viimase slaidi.","N or Notes: close this panel before showing the audience. Speaker notes share this window. \u2190 \u2192 navigates slides; Home / End opens the first / last slide.")}</p>`;}
function buildChooser(){let previousSection='';$('#chooser-list').innerHTML=SLIDES.map((s,i)=>{let header=s.section!==previousSection?`<li class="chooser-section" role="presentation">${s.section}</li>`:'';previousSection=s.section;return `${header}<li><button data-go="${i}" aria-current="${current===i}" ${current===i?'id="current-choice"':''}><span>${String(i+1).padStart(2,'0')}</span><span>${s.title}</span><small>${startMinute(i)}–${startMinute(i)+s.minutes} min</small></button></li>`;}).join('');}
function render(){updateChrome();const s=SLIDES[current];$('#stage').innerHTML=`<article class="slide" aria-labelledby="slide-title">${s.html()}</article>`;const heading=$('#stage h1,#stage h2');if(heading)heading.id='slide-title';$('#stage').scrollTop=0;$('#counter').textContent=`${current+1} / ${SLIDES.length}`;$('#timing').textContent=`${startMinute(current)}–${startMinute(current)+s.minutes} / ${total} min`;$('#previous').disabled=current===0;$('#next').disabled=current===SLIDES.length-1;$('#progress').style.width=`${(current+1)/SLIDES.length*100}%`;$('#announcement').textContent=`${tr("Slaid","Slide")} ${current+1} / ${SLIDES.length}: ${s.title}`;document.title=`${current+1}. ${s.title} — OpenMapStack`;updateNotes();buildChooser();bindDemo();}
function go(index){current=Math.max(0,Math.min(SLIDES.length-1,index));const hash=`#slaid-${current+1}`;if(location.hash!==hash)location.hash=hash;else render();}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function toggleNotes(force){notesOpen=force??!notesOpen;$('#notes').hidden=!notesOpen;$('#notes-toggle').setAttribute('aria-expanded',String(notesOpen));}
function updateDemo(){if($('#network-view'))$('#network-view').innerHTML=networkGraphic();if($('#chart-view'))$('#chart-view').innerHTML=chartGraphic();if($('#metric'))$('#metric').innerHTML=metricMarkup();if($('#walk-value'))$('#walk-value').textContent=demoState.minutes+' min';if($('#bridge-legend'))$('#bridge-legend').hidden=!demoState.bridge;}
function bindDemo(){if($('#walk-time'))$('#walk-time').addEventListener('input',e=>{demoState.minutes=Number(e.target.value);updateDemo();});if($('#bridge'))$('#bridge').addEventListener('change',e=>{demoState.bridge=e.target.checked;updateDemo();});if($('#weighted'))$('#weighted').addEventListener('change',e=>{demoState.weighted=e.target.checked;updateDemo();});}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast(tr('Täisekraan pole siin toetatud. Ava HTML brauseris või kasuta brauseri täisekraani.','Fullscreen is not supported here. Open the HTML in a browser or use the browser’s fullscreen mode.'));}catch{toast(tr('Täisekraan pole selles vaaturis lubatud. Ava HTML brauseris või kasuta F11.','Fullscreen is not allowed in this viewer. Open the HTML in a browser or use F11.'));}}
$('#next').addEventListener('click',()=>go(current+1));$('#previous').addEventListener('click',()=>go(current-1));$('#choose').addEventListener('click',()=>{$('#chooser').showModal();$('#current-choice')?.scrollIntoView({block:'center'});});$('#notes-toggle').addEventListener('click',()=>toggleNotes());$('#close-notes').addEventListener('click',()=>toggleNotes(false));$('#fullscreen').addEventListener('click',fullscreen);
document.addEventListener('fullscreenchange',updateFullscreenLabel);
for(const button of document.querySelectorAll('[data-language]'))button.addEventListener('click',()=>setLanguage(button.dataset.language));
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)document.getElementById(close.dataset.close).close();const choice=e.target.closest('[data-go]');if(choice){$('#chooser').close();go(Number(choice.dataset.go));}const image=e.target.closest('[data-image]');if(image){const img=image.querySelector('img');$('#lightbox-img').src=img.src;$('#lightbox-img').alt=img.alt;$('#lightbox-title').textContent=img.alt+tr(' · Tartu Emajõe kergliiklussillad',' · Tartu bridges · screenshot in Estonian');$('#lightbox').showModal();}});
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey||e.defaultPrevented)return;if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'&&notesOpen){toggleNotes(false);return;}const tag=document.activeElement?.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if(['BUTTON','A'].includes(tag)&&e.key===' ')return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(current+1);}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(current-1);}if(e.key==='Home'){e.preventDefault();go(0);}if(e.key==='End'){e.preventDefault();go(SLIDES.length-1);}if(e.key.toLowerCase()==='f')fullscreen();if(e.key.toLowerCase()==='n')toggleNotes();if(e.key.toLowerCase()==='g')$('#choose').click();});
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('hashchange',()=>{current=slideIndex();render();});
let swipeX=0,swipeY=0;$('#stage').addEventListener('touchstart',e=>{swipeX=e.changedTouches[0].clientX;swipeY=e.changedTouches[0].clientY;},{passive:true});$('#stage').addEventListener('touchend',e=>{if(e.target.closest('input,button,a'))return;const dx=e.changedTouches[0].clientX-swipeX,dy=e.changedTouches[0].clientY-swipeY;if(Math.abs(dx)>85&&Math.abs(dx)>Math.abs(dy)*1.8)go(current+(dx<0?1:-1));},{passive:true});
window.addEventListener('beforeprint',()=>{$('#stage').innerHTML=SLIDES.map(s=>`<article class="slide"><h2>${esc(s.title)}</h2>${s.html().replace(/<h[12][^>]*>[\s\S]*?<\/h[12]>/,'')}</article>`).join('');});window.addEventListener('afterprint',render);
current=slideIndex();render();
