// English deck: the same slides, timings and evidence as content.js.
const SLIDES_EN=[
{title:'OpenMapStack',minutes:1,section:'Question and framework',html:()=>`<div class="cover"><div><h1>OpenMapStack</h1><p class="lead">AI geospatial skills for reproducible map analysis</p><p class="sub">Tartu · a 15-minute walk · 45 min</p></div><div>${networkGraphic()}<p class="caption">Method illustration, not a measured result for Tartu.</p></div></div>`,notes:[
 'We already have GIS tools. What happens when an agent does the work from question to project?',
 'Show the workflow, limitations and inspectable artifacts. We will not run an hour-long data pipeline during this 45-minute session.',
 'The network graphic is synthetic and becomes interactive later.']},
{title:'Demo question: primary schools in Tartu',minutes:2,section:'Question and framework',html:()=>`<h2>One local question.</h2><p class="big-question">How well do Tartu’s primary schools cover the city <span class="em">within a 15-minute walk?</span></p>${flow([['Which schools?','Define primary school, operating institutions and entrances.'],['Which walk?','Street network, speed, bridges, crossings and access.'],['Coverage of what?','Dwellings, residents or children? Each denominator gives a different answer.']])}<p class="note-line">Author’s experience: the first usable result took roughly an hour. Correctness needs a separate review.</p>`,notes:[
 'Ask the audience what coverage should measure. Take two quick answers.',
 'The nearest school does not prove that a school place is available: capacity, age and catchment area are additional dimensions.',
 'Primary schools were the original case. The live demo shows its evolution: comparing the network effects of bridge locations over the Emajõgi in Tartu.']},
{title:'The 45-minute journey',minutes:1,section:'Question and framework',html:()=>`<h2>45 minutes: from question to decision</h2><div class="schedule"><div style="flex:16"><b>16 min</b><span>Agent, skill and project</span></div><div style="flex:15"><b>15 min</b><span>Method and guided demo</span></div><div style="flex:12"><b>12 min</b><span>Validation and product</span></div><div style="flex:2"><b>2 min</b><span>Discussion</span></div></div>${list([['What do we demonstrate?','The work becomes readable, runnable and verifiable.'],['What do we investigate?','Did the agent choose the right source, method and coverage denominator?'],['What does the GIS expert decide?','Which assumptions and limitations are acceptable for this decision?']])}`,notes:[
 'The schedule is calculated from slide durations: 16 + 15 + 12 + 2 = 45 minutes.',
 'The demo includes an offline illustration and the actual dashboard. If the connection fails, use the screenshots and illustration.']},
{title:'The prompt defines the analysis task',minutes:1,section:'Question and framework',html:()=>`<h2>The prompt defines the task.</h2><div class="prompt"><p>Analyse 15-minute walking coverage of operating primary schools in Tartu. Clarify which schools to include and measure coverage by dwellings.</p><p><em>Use the walkable network. Record sources, timestamps, CRS, assumptions and limitations. Create a reproducible OpenMapStack project, a map and a coverage sensitivity analysis for the time threshold.</em></p><p><em>If a required source or access information is missing, make that visible.</em></p></div><p class="note-line">The OpenMapStack skill adds the italicised requirements by default; you do not need to repeat them in the prompt.</p><p class="caption">Task wording prepared for this demo. <a href="https://claude.ai/share/f21cd0a5-02d3-411a-8575-238bf22e2b6d" target="_blank" rel="noopener">View the actual Claude conversation ↗</a></p>`,notes:[
 'The first paragraph is the user’s task. The two italicised paragraphs explain the skill’s default requirements; they do not need to appear in the actual prompt.',
 'The GIS expert reviews the concept and method rather than writing every line of Python.']},
{title:'Choose the agent and its capabilities',minutes:2,section:'Question and framework',html:()=>`<h2>Choose a tool that can do the work.</h2><div class="two"><div>${list([['Agent + skills','Load skills, write files and execute code.'],['Model capability','Start complex spatial work with a strong model and enough reasoning time.'],['Workspace','Desktop GUI, terminal, IDE or an isolated remote environment.']])}</div><div>${code(['Question','+ project folder','+ geospatial tools','+ an agent that uses them','+ your expert review','──────────────────────────','verifiable analysis'])}<p class="caption">ChatGPT, Claude, Gemini and DeepSeek are the context of the author’s trials. Capabilities depend on the specific agent, model and permissions.</p></div></div>`,notes:[
 'The author has preferred a strong model and high or higher reasoning effort where the tool supports it.',
 'Do not present a model ranking as a general benchmark. Compare the value and cost of a top model on your own task.',
 'A chat interface and an agent that executes code offer different workspaces. Products may support different skill formats.']},
{title:'Skills add detail; checks add confidence',minutes:2,section:'Question and framework',html:()=>`<h2>Skills add detail.<br>Checks add confidence.</h2>${flow([['Instructions','Source discovery, CRS, formats and workflow.'],['Choices','An open-first stack or the company’s existing technology.'],['Artifacts','Project, pipeline, provenance and selected outputs.'],['Evidence','Tests, evaluations and expert review of the result.']])}<div class="two"><p>A skill is readable, versioned guidance. Its value can be measured in agent behaviour.</p><p class="sub">Risk: a service, format or API changes. Verify specific claims against the source again.</p></div><p class="caption">Example skill catalogue: <a href="https://skills.sh/" target="_blank" rel="noopener">skills.sh</a> · a listing does not imply independent quality assurance.</p>`,notes:[
 'A skill does not automatically prove the method is correct. An agent can make mistakes even with good instructions.',
 'An opinionated stack narrows the search space; a company need not replace its existing stack.',
 'Separating the contribution of the model and skill requires comparable trials. One demo is a case study, not a generalisation. skills.sh homepage checked on 8 October 2026.']},
{title:'From context to data tools',minutes:2,section:'Question and framework',html:()=>`<h2>Data moves into tools.</h2><table class="table"><thead><tr><th>Data work</th><th>Tool</th><th>What does the expert check?</th></tr></thead><tbody><tr><td>Small sample</td><td>Model context</td><td>Does the sample represent the whole?</td></tr><tr><td>Structured files</td><td>Python · pandas · GeoPandas</td><td>Types, joins, nulls, geometry</td></tr><tr><td>Spatial computation</td><td>GDAL/OGR · PROJ · DuckDB · PostGIS</td><td>CRS, indexes, topology, units</td></tr><tr><td>Warehouses and services</td><td>BigQuery · MotherDuck · routing</td><td>Query scope, cost, permissions, provenance</td></tr></tbody></table><p class="note-line">There is no universal limit or price for model context. Large raw datasets stay in files or databases.</p>`,notes:[
 'The model writes the computation and reads a checked summary of its output.',
 'Structured data and code enable precise computation, but still require the right query and methodology.',
 'The draft’s 100K-token / $2 estimate depends on the model and tariff. Snowflake may be part of the company stack; this is not a promise of a built-in connector.']},
{title:'From conversation to reproducible project',minutes:2,section:'Question and framework',html:()=>`<h2>From question to a verifiable project</h2>${flow([['Question','Decision, scope and metric.'],['Skill + agent','Sources, method and implementation.'],['Project + pipeline','A readable contract and runnable computation.'],['Checks + output','Provenance, evidence and a usable map.']])}${code(['openmapstack validate project.yaml --preflight','openmapstack run project.yaml','openmapstack verify project.yaml'])}<p class="note-line">Conversation helps get the work done. The analysis dependencies must be readable in the project.</p>`,notes:[
 'The OpenMapStack CLI does not execute a chat prompt. run executes the declared canonical pipeline.',
 'Less dependence on prior chat may reduce context work; changes in speed and cost need measurement.',
 'The commands were checked against the parser in openmapstack/cli.py.']},
{title:'project.yaml is the analysis contract',minutes:2,section:'Question and framework',html:()=>`<h2>project.yaml: the analysis contract</h2><div class="two">${code(['<span class="comment"># Abbreviated Tartu example</span>','<span class="key">schema:</span> openmapstack-project/v1','<span class="key">project:</span>','  id: tartu-development-access','<span class="key">sources:</span>','  pedestrian_network: …','<span class="key">processing:</span>','  routing: …','<span class="key">overrides:</span> …','<span class="key">outputs:</span> …','<span class="key">validation:</span> …'])}${list([['Sources and assumptions','Where, when, which version and licence?'],['Steps and parameters','Which computation, CRS and threshold?'],['Results and evidence','What was produced, how was it checked, which run?']])}</div><p class="caption">This excerpt explains the structure; it is not a complete runnable manifest.</p>`,notes:[
 'Open project.yaml in an editor if needed. Do not read a long manifest aloud.',
 'Persistent explanations belong in data fields. The example pipeline reserialises YAML and may not preserve comments.',
 'SHA-256 and run evidence link a specific computation to specific files.']},
{title:'A workspace you can hand over',minutes:1,section:'Question and framework',html:()=>`<h2>A workspace you can hand over.</h2><div class="two project-files-slide">${code(['project.yaml       <span class="comment"># analysis contract</span>','pipeline.py        <span class="comment"># rerun</span>','requirements.txt   <span class="comment"># environment</span>','data/','  source/          <span class="comment"># source data</span>','  overrides/       <span class="comment"># changes</span>','  derived/         <span class="comment"># results</span>','validation/        <span class="comment"># check evidence</span>','runs/              <span class="comment"># run identity</span>','dashboard.html','README.md'])}<div>${list([['Files are the deliverable','GeoPackage, GeoParquet or GeoJSON, depending on the output.'],['The view is a choice','Dashboard; QGIS or an existing company view where needed.'],['The CLI is a tool','openmapstack is an installed runner and checker, rather than a file copied into every project.']])}</div></div>`,notes:[
 'The example also has project.qgz, but QGIS is not mandatory for every project.',
 'Source data and derived results are separate. Distinguish a cache from the authoritative source.',
 'The current implementation uses SHA-256, not the MD5 mentioned in the draft.']},
{title:'15 minutes along the network',minutes:3,section:'Method and demo',html:()=>`<h2>15 minutes along the network.</h2><div class="two wide"><div id="network-view">${networkGraphic()}</div><div>${list([['The network defines reach','Bridges, passages and breaks change travel time.'],['The destination defines access','Reaching a school requires the right entrance and network snapping.']])}${demoControls(true)}<p class="caption">Synthetic network. Times are edge weights; this illustration does not use Tartu data.</p></div></div>`,notes:[
 'Demo 1: change the time 15 → 10 → 20 minutes. Point out homes across the river. Add the synthetic bridge and show its network effect.',
 'This undirected synthetic graph uses Dijkstra. The bridges demo computes separate walking and cycling network scenarios.',
 'Direction, slopes, gates and time-dependent access can make real networks more complex. A spatial buffer does not automatically measure network accessibility.']},
{title:'The coverage denominator changes the answer',minutes:2,section:'Method and demo',html:()=>`<h2>Coverage of what?</h2><div class="two"><div><div class="legend-row"><span>Existing network</span><span class="alt" id="bridge-legend" ${demoState.bridge?'':'hidden'}>With a new bridge</span></div><div id="chart-view">${chartGraphic()}</div>${demoControls(false)}<p class="caption">Example data · discrete coverage in a synthetic network · not a Tartu result.</p></div><div><div id="metric">${metricMarkup()}</div><p class="note-line">Coverage = weight within the time threshold / total weight.</p><p class="sub" style="margin-top:18px">Counting residential buildings and weighting by dwellings are different metrics. Coverage of children needs age-group data.</p></div></div>`,notes:[
 'Demo 2: turn dwelling weights off and on. The same network gives a different percentage.',
 'Dwelling weights do not measure the number of children.',
 'Eurostat’s 1 km grid can be an additional check, but does not automatically locate people at building resolution. The historical comparison has not been recomputed here.']},
{title:'Five dashboard views',minutes:2,section:'Method and demo',html:()=>`<h2>A map you can interrogate.</h2><div class="two wide"><div>${shot('analysis','Bridge location comparison and a network-based recommendation')}</div>${steps([['All locations','Rank bridge locations and screen the entire river section.'],['Tuglase vs Marja','One bridge, the other or both.'],['Routes','Address pairs and scenario routes.'],['Map and provenance','Metrics, layers, sources and checks.']])}</div>`,notes:[
 'Actual application tabs (Estonian): Kõik kohad (All locations), Tuglase vs Marja, Teekonnad (Routes), Kaart (Map), Päritolu (Provenance).',
 'The original primary-school question evolved into an urban mobility question: where to add a connection and whose access improves?',
 'All locations compares planned bridges and screening locations derived every 100 m. Usage potential is a model index, not an observed count.']},
{title:'Guided demo: compare bridge locations',minutes:4,section:'Method and demo',html:()=>`<h2>Demo: compare bridges and travel modes.</h2><div class="two wide"><div>${shot('map','Map layers, impact metrics and sensitivity parameters')}</div><div>${steps([['Change bridge location','Compare Karlova, Tuglase, Marja and both together.'],['Change travel mode','Walking and cycling may produce different winners.'],['Change the metric','Accessibility, time saved or added floor area within a time threshold.']])}${demoLink()}</div></div>`,notes:[
 'Open the Tartu bridge analysis in a new tab; keep the presentation open. The live application and screenshots are in Estonian.',
 'Use the top menu to select Tuglase, Marja and Tuglase + Marja. Compare Jalgsi (Walking), Jalgrattaga (Cycling), Mõju (Impact) and Vahe Tuglasega (Difference from Tuglase).',
 'Map: switch Ligipääsetavuse kasv (%) (Accessibility increase) to Ajasääst keskmise teekonna kohta (s) (Average time saved per trip). Show that the winner depends on the metric.',
 'Sensitivity: gravity metric half-life 5/10/20 min; the walking threshold for added floor area 10/15/20 min. These are different parameters.',
 'If interrupted, use the screenshots and the offline illustration on slides 11–12.']},
{title:'Guided demo: inspect provenance',minutes:2,section:'Method and demo',html:()=>`<h2>The result must lead back to its sources.</h2><div class="two wide"><div>${shot('provenance','Data sources, versions and analysis provenance')}</div><div>${steps([['Source','Planning, buildings, population and road network.'],['Snapshot','Download time, version and run identity.'],['Method','Population allocation to buildings, speeds and distance decay.'],['Limitation','Access, uncalibrated usage and an untested check.']])}</div></div>`,notes:[
 'Open Päritolu (Provenance). Show the source list, assumptions, scenario additions and workflow.',
 'Residents are allocated to residential buildings by net floor area. This is a model assumption, not a register of actual residents in each building.',
 'Bridge usage potential is an uncalibrated gravity-model index. The order of magnitude of daily usage is tied to a separate observed count.',
 'The application report shows 28/29 checks passed: qgis_runtime_load is not tested. That is not a pass.']},
{title:'Guided demo: one bridge or both?',minutes:2,section:'Method and demo',html:()=>`<h2>One bridge, the other or both?</h2><div class="two wide"><div>${shot('comparison','Tuglase and Marja comparison and the value of a second bridge')}</div><div>${steps([['Compare individual bridges','Greater total impact and greater time savings are different things.'],['Add the second bridge','The combined effect need not equal the sum of individual effects.'],['Inspect a route','Show which network route becomes shorter.']])}<p class="note-line">Source data + a declared network change = a scenario.</p></div></div>`,notes:[
 'Open Tuglase vs Marja. Compare Üks, teine või mõlemad (One, the other or both) and Teise silla lisaväärtus (Value of the second bridge).',
 'This application adds bridges to walking and cycling networks. Show the difference between individual and combined scenarios.',
 'Teekonnad (Routes): select Supilinn (Marja tn) → Staadioni tn kool. The T/M/TM column shows the scenario route.',
 'Source data stays unchanged. Proposed bridge geometry comes from planning data; the pipeline checks the network connection.']},
{title:'The first prompt does not finish the job',minutes:2,section:'Validation and product development',html:()=>`<h2>The first prompt does not finish the job.</h2><div class="two"><div class="timeline"><div class="timeline-row"><b>1.0.1</b><div><p>Browser connected; checks repeated.</p><small>Does the view render? Do the buttons work?</small></div></div><div class="timeline-row"><b>2.0</b><div><p>Coverage dynamics and Tartu districts.</p><small>Walking time vs coverage; a table of gaps.</small></div></div><div class="timeline-row"><b>+ check</b><div><p>Eurostat’s 2021 population grid, 1 km.</p><small>Author’s finding: apartment weights were already included.</small></div></div><div class="timeline-row"><b>+ UX</b><div><p>School point clicks added with another tool.</p><small>The same workspace and clear artifacts.</small></div></div></div><div><p class="quote">Iteration refines both the question and the product.</p><p class="note-line">The author’s primary-school demo history. These versions and findings have not been independently confirmed from the repository example.</p></div></div>`,notes:[
 'This slide preserves the author’s historical account, not repository versioning.',
 'Distinguish improvements to the method, source clarification and UI fixes.',
 'Switching agents works better when the task and canonical pipeline are in files.']},
{title:'Browser and QGIS provide different evidence',minutes:2,section:'Validation and product development',html:()=>`<h2>Check the view where it is used.</h2><div class="two"><div>${list([['Browser','Rendering, layout, buttons, map layers and console errors.'],['QGIS / PyQGIS / MCP','The project opens, layers resolve, CRS and styles are appropriate.'],['Visualisation skills','Readable legends, metric units and honest comparisons.']])}</div><div>${shot('trips','Routes: visually checking the route and computed time')}</div></div><p class="caption">Automatic checks depend on the agent’s tools and environment. Missing capabilities must remain visible.</p>`,notes:[
 'Connection depends on the tool: built-in browser, plugin, Playwright or remote access. Universal Chrome support is not assumed.',
 'QGIS MCP helps when it is installed and available. The example runtime check may remain not_testable.',
 'A map or browser test alone does not prove that the analysis is correct.']},
{title:'Three layers of validation',minutes:2,section:'Validation and product development',html:()=>`<h2>What makes a result trustworthy?</h2><div class="two"><div class="status-list"><div class="status-row"><b class="em">passed</b><p>The check ran and the condition held.</p></div><div class="status-row"><b class="warning">warning</b><p>A visible limitation affects interpretation.</p></div><div class="status-row"><b>not_testable</b><p>A required capability was unavailable.</p></div><div class="status-row"><b class="warning">failed</b><p>The condition did not hold; fix the cause.</p></div></div><div>${code(['openmapstack validate project.yaml','<span class="comment"># manifest and required artifacts</span>','','openmapstack verify project.yaml','<span class="comment"># inspect produced artifacts</span>','','openmapstack verify project.yaml --rerun','<span class="comment"># clean rerun</span>'])}</div></div><p class="note-line">A reproducible wrong answer is still wrong. Check the concept and fitness for the decision.</p>`,notes:[
 'A clean rerun may take a long time. Do not start it unexpectedly on stage.',
 'not_testable is not passed. A valid report may include limitations.',
 'Example invariant: increasing the time threshold should not reduce coverage on a fixed network with the same denominator.']},
{title:'Time and money: one case study',minutes:2,section:'Validation and product development',html:()=>`<h2>Time and money: one case study.</h2><div class="costs"><div><div class="huge em">~1<span class="unit"> h</span></div><p>One analysis iteration.</p></div><div><div class="huge em">~150<span class="unit">K</span></div><p>Tokens per iteration.</p></div><div><div class="huge">~10</div><p>Updates over 1–2 weeks.</p></div></div><div class="two"><p>The initial question + two follow-up prompts gave the author’s demo a usable direction.</p><p class="sub">Track costs separately: model, retries, routing, warehouse and expert review time.</p></div><p class="note-line">Author’s estimates, not a benchmark or price list. Subscription usage limits differ from token-based API spend.</p>`,notes:[
 '150K tokens is an approximate experience-based estimate. Exact accounting requires logs and the model tariff.',
 'The draft’s Pro-plan price and session window describe the author’s experience at the time, not general pricing.',
 'Compare the same task and quality criteria. A smaller local model is a goal, not a proven equivalent replacement.']},
{title:'Private data and partial updates',minutes:2,section:'Validation and product development',html:()=>`<h2>Private data. Explicit changes.</h2>${flow([['Private source','PostGIS, MotherDuck or BigQuery; a scoped query.'],['Snapshot','Parquet / GeoParquet with query and identity.'],['Processing','CLI + SQL / DuckDB Spatial / Python.'],['New result','A validated rerun and run evidence.']])}<div class="two"><p><span class="em">Data change:</span> a separate override, rationale and baseline comparison.</p><p class="sub">Define which data and summaries reach the agent or model service.</p></div><p class="note-line">An override does not automatically mean incremental computation. Update scope depends on the pipeline.</p>`,notes:[
 'The repository has PostGIS, MotherDuck and BigQuery connectors. The company’s data platform need not change.',
 'A file may remain local, but tool output and prompts can carry data to a model service. Define the data-flow boundary.',
 'A new bridge must change the correct computation. A change file does not prove the routing graph was rebuilt.']},
{title:'Product focus: what should we build next?',minutes:1,section:'Validation and product development',html:()=>`<h2>What should we build next?</h2>${list([['First goal: reusable analysis','From a task to a transferable project and a verifiable result.'],['Next goal: safe updates','Data flow, permissions, accepting overrides and comparing runs.'],['Research direction: smaller models and streaming','Local execution, event-driven updates and persistent freshness need separate implementation.']])}<p class="note-line">Real-time streaming is not implemented in this demo. We show a snapshot-based workflow.</p>`,notes:[
 'Discuss integration boundaries: which part is the agent, the worker and the checker?',
 'Streaming is a proposed future direction, not a confirmed delivery commitment.']},
{title:'What should you take away?',minutes:1,section:'Validation and product development',html:()=>`<h2>A good result stays in the folder.</h2><p class="quote">The agent does the work.<br><span class="em">The project preserves the method.</span><br>The GIS expert judges its meaning.</p><div class="source-links"><a href="${REPO}" target="_blank" rel="noopener">OpenMapStack repository ↗</a><a href="https://jaakla.github.io/openmapstack-skills/" target="_blank" rel="noopener">Homepage and working examples ↗</a><a href="${PUBLIC_DEMO}" target="_blank" rel="noopener">Tartu bridge analysis and its provenance ↗</a></div><p class="caption">Technical sources: README · project.yaml · pipeline.py · cli.py · validation/latest-report.json. Presentation basis: the author’s demo experience.</p>`,notes:[
 'Three ideas: a file-based contract, the right spatial concept and visible validation.',
 'The installation command and exact version are in the repository README. Links open in a separate tab.']},
{title:'Discussion: where would you pilot this?',minutes:2,section:'Discussion',html:()=>`<h2>Where would you pilot this?</h2><div class="discussion"><div><h3>One decision</h3><p>Which spatial question do you repeatedly answer manually?</p></div><div><h3>One check</h3><p>Which error would make the result unusable?</p></div><div><h3>One boundary</h3><p>Which data and permissions stay in your environment?</p></div></div><p class="note-line">Pilot deliverable: the same question and metric, a visible method, a repeatable run and expert judgement.</p>`,notes:[
 'Take one concrete pilot example. If time is short, choose only the validation question.',
 'Bring the discussion back to the task and quality bar. End at 45 minutes; the slide chooser helps with follow-up questions.']}
];
