// Actual Tartu bridges dashboard screenshots are embedded by build.py.
const IMAGES = __IMAGES__;
const REPO='https://github.com/jaakla/openmapstack-skills';
const PUBLIC_DEMO='https://tartu-sillad.jaak-laineste.workers.dev/';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const list=items=>`<ul class="list">${items.map(([title,text])=>`<li><strong>${title}</strong><span>${text}</span></li>`).join('')}</ul>`;
const steps=items=>`<div class="steps">${items.map(([title,text],i)=>`<div class="step-row"><b>${i+1}</b><div><h3>${title}</h3><p>${text}</p></div></div>`).join('')}</div>`;
const flow=items=>`<div class="flow ${items.length===3?'three':''}">${items.map(([title,text],i)=>`<div class="step"><b class="num">${i+1}</b><h3>${title}</h3><p>${text}</p></div>`).join('')}</div>`;
const code=lines=>`<pre class="code">${lines.join('\n')}</pre>`;
const shot=(key,label)=>`<div class="screenshot-frame"><div class="photo-label">${tr("Päris demo: Tartu Emajõe kergliiklussillad","Actual demo: Tartu bridges · screenshot in Estonian")}</div><button class="photo-button" data-image="${key}" aria-label="${tr("Suurenda ekraanipilti","Enlarge screenshot")}: ${esc(label)}"><img class="photo" src="${IMAGES[key]}" alt="${esc(label)}"></button><p class="caption">${label}. ${tr("Klõpsa pildil suurendamiseks.","Click the image to enlarge.")}</p></div>`;
const demoLink=()=>`<a class="demo-link" href="${PUBLIC_DEMO}" target="_blank" rel="noopener">${tr("Ava Tartu sillaanalüüs ↗","Open Tartu bridge analysis ↗")}</a>`;

const SLIDES_ET=[
{title:'OpenMapStack',minutes:1,section:'Küsimus ja raamistik',html:()=>`<div class="cover"><div><h1>OpenMapStack</h1><p class="lead">Tehisintellekti geo-oskused korratavaks kaardianalüüsiks</p><p class="sub">Tartu · 15 minuti jalutuskäik · 45 min</p></div><div>${networkGraphic()}<p class="caption">Meetodi skeem, mitte Tartu mõõtmistulemus.</p></div></div>`,notes:[
 'GIS-tööriistad on meil olemas. Mis juhtub, kui küsimusest projektini viiva töö teeb agent?',
 'Näita töö käiku, piiranguid ja kontrollitavaid artefakte. 45 minuti sees ei käivita me tunnist andmepipeline’i.',
 'Kaardigraafika on sünteetiline ja on hiljem interaktiivne.']},
{title:'Demoküsimus: Tartu algkoolid',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>Üks kohalik küsimus.</h2><p class="big-question">Kui hea on Tartu algkoolide katvus <span class="em">15 minuti jalutuskäiguga?</span></p>${flow([['Millised koolid?','Algkooli definitsioon, tegutsevad asutused, sissepääsud.'],['Milline jalutuskäik?','Tänavavõrk, kiirus, sillad, ülekäigud ja ligipääs.'],['Katvus millest?','Eluruumid, elanikud või lapsed? Iga nimetaja annab eri vastuse.']])}<p class="note-line">Autori kogemus: esimene kasutatav tulemus ligikaudu tunniga. Sisuline õigsus vajab eraldi kontrolli.</p>`,notes:[
 'Küsi publikult suuliselt, mida katvuse all mõõta. Võta kaks kiiret vastust.',
 'Lähim kool ei tõenda koolikoha kättesaadavust: mahutavus, vanus ja teeninduspiirkond on lisamõõtmed.',
 'Algkoolide küsimus on algne lähtejuhtum. Live-demo näitab edasiarendust: Tartu Emajõe sillakohtade võrgumõju võrdlust.']},
{title:'45 minuti teekond',minutes:1,section:'Küsimus ja raamistik',html:()=>`<h2>45 minutit: küsimusest otsuseni</h2><div class="schedule"><div style="flex:16"><b>16 min</b><span>Agent, skill ja projekt</span></div><div style="flex:15"><b>15 min</b><span>Meetod ja juhitud demo</span></div><div style="flex:12"><b>12 min</b><span>Kontroll ja tootearendus</span></div><div style="flex:2"><b>2 min</b><span>Arutelu</span></div></div>${list([['Mida me tõendame?','Töö muutub loetavaks, käivitatavaks ja kontrollitavaks.'],['Mida me uurime?','Kas agent valis õige allika, meetodi ja katvuse nimetaja?'],['Mida GIS-ekspert otsustab?','Millised eeldused ja piirangud on selle otsuse jaoks vastuvõetavad?']])}`,notes:[
 'Ajajaotus on slaidide kestustest arvutatud: 16 + 15 + 12 + 2 = 45 minutit.',
 'Demo sisaldab offline-skeemi ja tegeliku dashboardi avamist. Võrguprobleemi korral jää ekraanipiltide ja skeemi juurde.']},
{title:'Prompt on analüüsi lähteülesanne',minutes:1,section:'Küsimus ja raamistik',html:()=>`<h2>Prompt on lähteülesanne.</h2><div class="prompt"><p>Analüüsi Tartu tegutsevate algkoolide 15 minuti jalgsikatvust. Täpsusta koolide valik ja mõõda katvust eluruumide järgi.</p><p><em>Kasuta kõnnitavat võrku. Salvesta allikad, ajad, CRS, eeldused ja piirangud. Loo korratav OpenMapStacki projekt, kaart ning katvuse tundlikkus ajapiiri suhtes.</em></p><p><em>Kui vajalik allikas või ligipääsuinfo puudub, too see nähtavale.</em></p></div><p class="note-line">Kursiivis nõuded lisab OpenMapStacki oskus vaikimisi; neid pole vaja promptis korrata.</p><p class="caption">Demoks koostatud lähteülesanne. <a href="https://claude.ai/share/f21cd0a5-02d3-411a-8575-238bf22e2b6d" target="_blank" rel="noopener">Vaata päris Claude’i vestlust ↗</a></p>`,notes:[
 'Esimene lõik on kasutaja lähteülesanne. Kaks kursiivis lõiku selgitavad OpenMapStacki oskuse vaikimisi nõudeid; neid pole vaja tegelikus promptis korrata.',
 'GIS-eksperdi panus on mõiste ja meetodi ülevaatus, mitte iga Python-rea kirjutamine.']},
{title:'Vali agent ja võimekus',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>Vali töövahend, mis saab tööd teha.</h2><div class="two"><div>${list([['Agent + oskused','Oskuste laadimine, failide kirjutamine ja koodi käivitamine.'],['Mudeli võimekus','Keeruka ruumilise töö jaoks alusta tugevast mudelist ja piisavast mõtlemisajast.'],['Tööpind','Desktop GUI, terminal, IDE või eraldatud kaugkeskkond.']])}</div><div>${code(['Küsimus','+ projektikaust','+ geotööriistad','+ agent, kes neid kasutab','+ sinu sisuline ülevaatus','──────────────────────────','kontrollitav analüüs'])}<p class="caption">ChatGPT, Claude, Gemini ja DeepSeek on autori katsetuste kontekst. Võimekus sõltub konkreetsest agendist, mudelist ja õigustest.</p></div></div>`,notes:[
 'Autori eelistus on olnud tugev mudel ning high või kõrgem mõtlemistase, kui töövahend seda võimaldab.',
 'Ära esita mudelite paremusjärjestust üldise benchmark’ina. Tippmudeli lisaväärtus ja hind tuleb oma ülesande peal võrrelda.',
 'Tavaline vestlusliides ja koodi käivitav agent ei anna sama tööpinda. Iga toode ei pruugi toetada sama skill-formaati.']},
{title:'Skill annab detailid, kontroll annab kindluse',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>Oskus annab detailid.<br>Kontroll annab kindluse.</h2>${flow([['Juhised','Allikate leidmine, CRS, formaadid ja töövoog.'],['Valikud','Open-first stack või olemasolev ettevõtte tehnoloogia.'],['Artefaktid','Projekt, pipeline, päritolu ja valitud väljundid.'],['Tõendid','Testid, eval’id ja tulemuse sisuline ülevaatus.']])}<div class="two"><p>Skill on loetav ja versioonitav juhis. Selle väärtust saab mõõta agentide käitumises.</p><p class="sub">Risk: teenus, formaat või API muutub. Täpne väide tuleb allikast uuesti kontrollida.</p></div><p class="caption">Oskuste kataloogi näide: <a href="https://skills.sh/" target="_blank" rel="noopener">skills.sh</a> · kataloog ei tähenda iga oskuse sõltumatut kvaliteedikontrolli.</p>`,notes:[
 'Skill ei tõesta automaatselt, et meetod on õige. Ka hästi kirjutatud juhisega agent võib eksida.',
 'Opinionated stack vähendab otsinguruumi, kuid ettevõtte olemasolevat stack’i ei pea välja vahetama.',
 'Mudeli ja skilli panuse eristamiseks on vaja võrreldavaid katseid. Üks demo on juhtum, mitte üldistus. skills.sh avaleht vaadatud 08.10.2026.']},
{title:'Andmed kontekstist tööriistadesse',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>Andmed liiguvad tööriistadesse.</h2><table class="table"><thead><tr><th>Andmetöö</th><th>Töövahend</th><th>Mida ekspert kontrollib?</th></tr></thead><tbody><tr><td>Väike väljavõte</td><td>Mudeli kontekst</td><td>Kas näidis esindab tervikut?</td></tr><tr><td>Struktureeritud failid</td><td>Python · pandas · GeoPandas</td><td>Tüübid, join’id, nullid, geomeetria</td></tr><tr><td>Ruumiline arvutus</td><td>GDAL/OGR · PROJ · DuckDB · PostGIS</td><td>CRS, indeksid, topoloogia, ühikud</td></tr><tr><td>Andmeladu ja teenused</td><td>BigQuery · MotherDuck · ruutimine</td><td>Päringu ulatus, kulud, õigused, päritolu</td></tr></tbody></table><p class="note-line">Mudeli konteksti mahul ja hinnal pole üht universaalset piiri. Suured toorandmed jäävad failidesse või andmebaasi.</p>`,notes:[
 'Mudel kirjutab arvutuse ja loeb selle kontrollitud kokkuvõtet.',
 'Struktureeritud andmed ja kood võimaldavad täpset arvutust, mis eeldab siiski õiget päringut ja metoodikat.',
 'Drafti 100K tokeni / 2 dollari hinnang sõltub mudelist ja tariifist. Snowflake võib olla ettevõtte stack, mitte lubadus sisseehitatud connector’ist.']},
{title:'Vestlusest korratavaks projektiks',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>Küsimusest kontrollitava projektini</h2>${flow([['Küsimus','Otsus, ulatus ja mõõdik.'],['Skill + agent','Allikad, meetod ja teostus.'],['Projekt + pipeline','Loetav leping ja käivitatav arvutus.'],['Kontroll + väljund','Päritolu, tõendid ja kasutatav kaart.']])}${code(['openmapstack validate project.yaml --preflight','openmapstack run project.yaml','openmapstack verify project.yaml'])}<p class="note-line">Vestlus aitab tööd teha. Analüüsi sõltuvused peavad olema projektis loetavad.</p>`,notes:[
 'OpenMapStacki CLI ei käivita vestlusprompti. run käivitab deklareeritud canonical pipeline’i.',
 'Vähem varasemast chatist sõltumist võib vähendada uut kontekstitööd; kiiruse ja hinna muutus vajab mõõtmist.',
 'Käsud on kontrollitud hoidla openmapstack/cli.py parseri järgi.']},
{title:'project.yaml on analüüsi leping',minutes:2,section:'Küsimus ja raamistik',html:()=>`<h2>project.yaml: analüüsi leping</h2><div class="two">${code(['<span class="comment"># Tartu näite lühendatud struktuur</span>','<span class="key">schema:</span> openmapstack-project/v1','<span class="key">project:</span>','  id: tartu-development-access','<span class="key">sources:</span>','  pedestrian_network: …','<span class="key">processing:</span>','  routing: …','<span class="key">overrides:</span> …','<span class="key">outputs:</span> …','<span class="key">validation:</span> …'])}${list([['Allikad ja eeldused','Kust, millal, mis versioon, mis litsents?'],['Sammud ja parameetrid','Milline arvutus, mis CRS ja milline lävi?'],['Tulemus ja tõendid','Mida väljastati, kuidas kontrolliti, milline käivitus?']])}</div><p class="caption">Väljavõte selgitab struktuuri; see ei ole käivitatav tervikmanifest.</p>`,notes:[
 'Ava vajadusel project.yaml editoris. Ära loe pikka manifesti ette.',
 'Püsivad seletused tuleb panna andmeväljadele. Näite pipeline serialiseerib YAML-i uuesti ega säilita tingimata kommentaare.',
 'SHA-256 ja jooksu tõendid seovad konkreetse arvutuse konkreetsete failidega.']},
{title:'Töökaust on üleantav tulemus',minutes:1,section:'Küsimus ja raamistik',html:()=>`<h2>Töökaust, mille saad üle anda.</h2><div class="two project-files-slide">${code(['project.yaml       <span class="comment"># analüüsi leping</span>','pipeline.py        <span class="comment"># korduskäivitus</span>','requirements.txt   <span class="comment"># keskkond</span>','data/','  source/          <span class="comment"># algandmed</span>','  overrides/       <span class="comment"># muudatused</span>','  derived/         <span class="comment"># tulemused</span>','validation/        <span class="comment"># kontrollitõendid</span>','runs/              <span class="comment"># jooksu identiteet</span>','dashboard.html','README.md'])}<div>${list([['Failid jäävad töö tulemuseks','GeoPackage, GeoParquet või GeoJSON vastavalt väljundile.'],['Vaade on valik','Dashboard; vajadusel QGIS või ettevõtte olemasolev vaade.'],['CLI on töövahend','openmapstack on paigaldatud käivitaja ja kontrollija, mitte iga projekti kopeeritud fail.']])}</div></div>`,notes:[
 'Näites on ka project.qgz, kuid QGIS ei ole kohustuslik igale projektile.',
 'Algandmed ja tuletatud tulemused on eraldi. Vahemälu peab olema eristatav ametlikust allikast.',
 'Praegune teostus kasutab SHA-256, mitte draftis mainitud MD5.']},
{title:'15 minutit mööda võrku',minutes:3,section:'Meetod ja demo',html:()=>`<h2>15 minutit mööda võrku.</h2><div class="two wide"><div id="network-view">${networkGraphic()}</div><div>${list([['Võrk määrab ulatuse','Sillad, läbipääsud ja katkestused muudavad aega.'],['Sihtpunkt määrab ligipääsu','Koolini jõudmine vajab õiget sissepääsu ja snap’i.']])}${demoControls(true)}<p class="caption">Sünteetiline võrk. Ajad on servade kaalud; skeem ei kasuta Tartu andmeid.</p></div></div>`,notes:[
 'Demo 1: liiguta aega 15 → 10 → 20 minutit. Osuta üle jõe paiknevatele majadele. Lisa sünteetiline sild ja näita võrgumõju.',
 'Selles suunamata sünteetilises võrgus on Dijkstra arvutus; sillademo arvutab eraldi jalgsi- ja rattavõrgu stsenaariumid.',
 'Kõnni suund, tõusud, väravad ja ajaline ligipääs võivad päris võrgu keerukamaks muuta. Ruumiline puhver ei ole automaatselt võrgupõhine ligipääsetavus.']},
{title:'Katvuse nimetaja muudab vastust',minutes:2,section:'Meetod ja demo',html:()=>`<h2>Katvus millest?</h2><div class="two"><div><div class="legend-row"><span>Olemasolev võrk</span><span class="alt" id="bridge-legend" ${demoState.bridge?'':'hidden'}>Uue sillaga</span></div><div id="chart-view">${chartGraphic()}</div>${demoControls(false)}<p class="caption">Näidisandmed · diskreetne katvus sünteetilises võrgus · ei ole Tartu tulemus.</p></div><div><div id="metric">${metricMarkup()}</div><p class="note-line">Katvus = ajapiiri sees olev kaal / kogu kaal.</p><p class="sub" style="margin-top:18px">Elumajade loend ja eluruumide kaal on eri mõõdikud. Laste katvus vajab vanuserühma andmeid.</p></div></div>`,notes:[
 'Demo 2: lülita eluruumide kaal välja ja tagasi sisse. Sama võrk annab teise protsendi.',
 'Eluruumide kaal ei võrdu laste arvu mõõtmisega.',
 'Eurostati 1 km ruudustik võib olla lisakontroll, kuid ei anna automaatselt hoone täpsusega paiknemist. Ajalooline võrdlus ei ole siin uuesti arvutatud.']},
{title:'Dashboardi viis vaadet',minutes:2,section:'Meetod ja demo',html:()=>`<h2>Kaart, mida saab küsitleda.</h2><div class="two wide"><div>${shot('analysis','Sillakohtade võrdlus ja soovitus võrgumõju põhjal')}</div>${steps([['Kõik kohad','Sillakohtade järjestus ja kogu jõelõigu sõelumine.'],['Tuglase vs Marja','Üks sild, teine sild või mõlemad.'],['Teekonnad','Aadressipaarid ja stsenaariumide marsruudid.'],['Kaart ja päritolu','Mõõdikud, kihid, allikad ja kontrollid.']])}</div>`,notes:[
 'Demorakenduse päris vaated: Kõik kohad, Tuglase vs Marja, Teekonnad, Kaart, Päritolu.',
 'Algne algkoolide küsimus on kasvanud linna liikuvuse küsimuseks: kuhu lisada uus ühendus ja kelle ligipääs paraneb?',
 'Kõik kohad võrdleb planeeritud sillakohti ja iga 100 m järel tuletatud sõelumiskohti. Kasutuspotentsiaal on mudeli indeks, mitte loendus.']},
{title:'Juhitud demo: võrdle sillakohti',minutes:4,section:'Meetod ja demo',html:()=>`<h2>Demo: võrdle sildu ja liikumisviise.</h2><div class="two wide"><div>${shot('map','Kaardikihid, mõjumõõdikud ja tundlikkuse parameetrid')}</div><div>${steps([['Vaheta sillakohta','Võrdle Karlovat, Tuglast, Marjat ja mõlemat koos.'],['Vaheta liikumisviisi','Jalgsi ja jalgrattaga võivad võitjad erineda.'],['Muuda mõõdikut','Ligipääsetavus, ajasääst või ajaläve piires lisanduv pind.']])}${demoLink()}</div></div>`,notes:[
 'Ava Tartu sillaanalüüs uuel tab’il; jäta esitlus alles.',
 'Vali ülemisest menüüst Tuglase, Marja ja Tuglase + Marja; võrdle Jalgsi ja Jalgrattaga ning Mõju / Vahe Tuglasega.',
 'Kaart: vaheta Ligipääsetavuse kasv (%) → Ajasääst keskmise teekonna kohta (s). Näita, et võitja sõltub mõõdikust.',
 'Tundlikkus: gravitatsioonimõõdiku poolestusaeg 5/10/20 min; lisanduva pinna ajalävi jalgsi 10/15/20 min. Need on eri parameetrid.',
 'Katkestuse korral kasuta ekraanipilte ja slaidide 11–12 offline-skeemi.']},
{title:'Juhitud demo: vaata päritolu',minutes:2,section:'Meetod ja demo',html:()=>`<h2>Tulemus peab viima allikani.</h2><div class="two wide"><div>${shot('provenance','Andmeallikad, versioonid ja analüüsi päritolu')}</div><div>${steps([['Allikas','Planeering, hooned, rahvastik ja teedevõrk.'],['Hetkeseis','Allalaadimise aeg, versioon ja käivituse identiteet.'],['Meetod','Elanike jaotus hoonetele, kiirused ja kaugusekaal.'],['Piirang','Juurdepääs, kalibreerimata kasutus ja testimata kontroll.']])}</div></div>`,notes:[
 'Ava Päritolu. Näita allikate loendit, eeldusi, stsenaariumi lisandusi ja töövoogu.',
 'Elanikud jaotatakse elamutele netopinna alusel; see on mudelieeldus, mitte iga hoone tegelike elanike register.',
 'Silla kasutuspotentsiaal on kalibreerimata gravitatsioonimudeli indeks. Päevase kasutuse suurusjärk on seotud eraldi loendusega.',
 'Rakenduse raportis on 28/29 kontrolli läbitud: qgis_runtime_load on ei testitud. See ei ole sama mis läbitud.']},
{title:'Juhitud demo: üks sild või mõlemad?',minutes:2,section:'Meetod ja demo',html:()=>`<h2>Üks sild, teine või mõlemad?</h2><div class="two wide"><div>${shot('comparison','Tuglase ja Marja võrdlus ning teise silla lisaväärtus')}</div><div>${steps([['Võrdle üksiksildu','Suurem kogumõju ja suurem ajasääst pole sama asi.'],['Lisa teine sild','Koosmõju ei pea olema üksikmõjude summa.'],['Vaata teekonda','Näita võrgus, milline marsruut lüheneb.']])}<p class="note-line">Algandmed + deklareeritud võrgumuudatus = stsenaarium.</p></div></div>`,notes:[
 'Ava Tuglase vs Marja. Võrdle ridu Üks, teine või mõlemad ning Teise silla lisaväärtus.',
 'Sillad lisatakse selles rakenduses jalgsi- ja rattavõrku. Näita erinevust üksiksilla ja kombineeritud stsenaariumi vahel.',
 'Teekonnad: vali Supilinn (Marja tn) → Staadioni tn kool; T/M/TM veerg näitab eri stsenaariumi marsruuti.',
 'Algandmed ei muutu; kavandatavate sildade geomeetria tuleb planeeringust ning seost kontrollib pipeline.']},
{title:'Esimene prompt ei lõpeta tööd',minutes:2,section:'Kontroll ja tootearendus',html:()=>`<h2>Esimene prompt ei lõpeta tööd.</h2><div class="two"><div class="timeline"><div class="timeline-row"><b>1.0.1</b><div><p>Brauser ühendati; kontroll korrati.</p><small>Kas vaade renderdub ja nupud töötavad?</small></div></div><div class="timeline-row"><b>2.0</b><div><p>Katvuse dünaamika ja Tartu asumid.</p><small>Jalutusaeg vs katvus; aukude tabel.</small></div></div><div class="timeline-row"><b>+ kontroll</b><div><p>Eurostati 2021. aasta 1 km ruudustik.</p><small>Autori järeldus: kortermajade kaal oli juba sees.</small></div></div><div class="timeline-row"><b>+ UX</b><div><p>Koolipunkti klikk teise töövahendiga.</p><small>Sama töökaust, selged artefaktid.</small></div></div></div><div><p class="quote">Iteratsioon täpsustab nii küsimust kui ka toodet.</p><p class="note-line">Autori algkoolide demo ajalugu. Neid versioone ja järeldusi ei ole hoidla näite põhjal sõltumatult kinnitatud.</p></div></div>`,notes:[
 'See slaid säilitab autori antud ajaloolise loo, mitte hoidla versioneerimise.',
 'Erista meetodi parandust, allika täpsustust ja UI-parandust.',
 'Agentide vahetamine toimib paremini, kui lähteülesanne ja canonical pipeline on failides.']},
{title:'Brauser ja QGIS annavad eri tõendeid',minutes:2,section:'Kontroll ja tootearendus',html:()=>`<h2>Kontrolli vaadet seal, kus seda kasutatakse.</h2><div class="two"><div>${list([['Brauser','Renderdus, layout, nupud, kaardikihid ja konsooli vead.'],['QGIS / PyQGIS / MCP','Projekt avaneb, kihid leitakse, CRS ja stiilid sobivad.'],['Visualiseerimise oskused','Loetav legend, mõõdiku ühikud ja ausad võrdlused.']])}</div><div>${shot('trips','Teekonnad: marsruudi ja arvutatud aja visuaalne kontroll')}</div></div><p class="caption">Automaatne kontroll sõltub agendi tööriistadest ja keskkonnast. Puuduv võimekus peab jääma nähtavaks.</p>`,notes:[
 'Ühendus sõltub töövahendist: sisseehitatud brauser, plugin, Playwright või kaugühendus. Universaalset Chrome’i tuge ei eeldata.',
 'QGIS MCP aitab siis, kui see on paigaldatud ja kasutatav. Näite runtime kontroll võib jääda not_testable.',
 'Kaart ega brauseritest ei tõenda üksi analüüsi õigsust.']},
{title:'Kolm kontrollikihti',minutes:2,section:'Kontroll ja tootearendus',html:()=>`<h2>Mis annab tulemusele usaldusväärsuse?</h2><div class="two"><div class="status-list"><div class="status-row"><b class="em">passed</b><p>Kontroll jooksis ja tingimus täitus.</p></div><div class="status-row"><b class="warning">warning</b><p>Tulemusel on nähtav tõlgenduspiir.</p></div><div class="status-row"><b>not_testable</b><p>Vajalik võimekus puudus.</p></div><div class="status-row"><b class="warning">failed</b><p>Tingimus ei täitunud; paranda põhjus.</p></div></div><div>${code(['openmapstack validate project.yaml','<span class="comment"># manifest ja nõutud artefaktid</span>','','openmapstack verify project.yaml','<span class="comment"># toodetud artefaktide kontroll</span>','','openmapstack verify project.yaml --rerun','<span class="comment"># puhas korduskäivitus</span>'])}</div></div><p class="note-line">Reprodutseeritav vale vastus on endiselt vale vastus. Kontrolli mõistet ja otsuse sobivust.</p>`,notes:[
 'Puhas korduskäivitus võib võtta kaua; ära käivita seda laval ootamatult.',
 'not_testable ei ole passed. Õige raport võib sisaldada piiranguid.',
 'Invariandi näide: ajapiiri suurendamine ei tohiks fikseeritud võrgus ja sama nimetajaga katvust vähendada.']},
{title:'Aeg ja raha: ühe juhtumi kogemus',minutes:2,section:'Kontroll ja tootearendus',html:()=>`<h2>Aeg ja raha: ühe juhtumi kogemus.</h2><div class="costs"><div><div class="huge em">~1<span class="unit"> h</span></div><p>Üks analüüsi iteratsioon.</p></div><div><div class="huge em">~150<span class="unit">K</span></div><p>Tokenit iteratsiooni kohta.</p></div><div><div class="huge">~10</div><p>Täiendust 1–2 nädala jooksul.</p></div></div><div class="two"><p>Esimene küsimus + kaks täpsustavat prompti andsid autori demole kasutatava suuna.</p><p class="sub">Jälgi kulu eraldi: mudel, kordused, ruutimine, andmeladu ja eksperdi kontrollaeg.</p></div><p class="note-line">Autori hinnangud, mitte benchmark ega hinnakiri. Tellimuse kasutuslimiit ei ole sama mis tokenipõhine API kulu.</p>`,notes:[
 '150K tokenit on ligikaudne kogemushinnang. Täpne arvestus vajab logi ja mudeli tariifi.',
 'Drafti Pro-plaani hind ja sessiooniaken on tollane kasutuskogemus, mitte üldine hinnaväide.',
 'Võrdle sama töö ja kvaliteedikriteeriumiga läbimist. Väiksem kohalik mudel on siht, mitte tõendatud võrdväärne asendus.']},
{title:'Privaatandmed ja osalised uuendused',minutes:2,section:'Kontroll ja tootearendus',html:()=>`<h2>Privaatandmed. Selged muudatused.</h2>${flow([['Privaatallikas','PostGIS, MotherDuck või BigQuery; piiratud ulatusega päring.'],['Hetkeseis','Parquet / GeoParquet koos päringu ja identiteediga.'],['Töötlus','CLI + SQL / DuckDB Spatial / Python.'],['Uus tulemus','Kontrollitud korduskäivitus ja jooksu tõend.']])}<div class="two"><p><span class="em">Andmemuudatus:</span> eraldi override, põhjendus ja baseline’i võrdlus.</p><p class="sub">Määratle, millised andmed ja kokkuvõtted agenti või mudeliteenusesse jõuavad.</p></div><p class="note-line">Override ei tähenda automaatselt inkrementaalset arvutust. Uuenduse ulatus sõltub pipeline’ist.</p>`,notes:[
 'Hoidlas on PostGISi, MotherDucki ja BigQuery connector’id. Ettevõtte andmeplatvorm ei pea muutuma.',
 'Fail võib jääda kohalikuks, kuid tool-output ja prompt võivad andmeid mudeliteenusesse viia. Määra andmevoo piir.',
 'Uus sild peab muutma õiget arvutust. Muudatusefail ei tõenda, et ruutimisgraaf taastati.']},
{title:'Tootefookus: mida edasi ehitada?',minutes:1,section:'Kontroll ja tootearendus',html:()=>`<h2>Mida edasi ehitada?</h2>${list([['Esimene siht: korduskasutatav analüüs','Lähteülesandest üleantav projekt ja kontrollitav tulemus.'],['Järgmine siht: turvaline uuendus','Andmevoog, õigused, override’i aktsepteerimine ja jooksude võrdlus.'],['Uuritav suund: väiksemad mudelid ja streaming','Kohalik täitmine, sündmuspõhised uuendused ja püsiv värskus vajavad eraldi teostust.']])}<p class="note-line">Reaalaja andmevoog ei ole demos teostatud. Näitame snapshot’il põhinevat töövoogu.</p>`,notes:[
 'Arutle integratsioonipiiridest: milline osa on agent, milline worker, milline kontrollija?',
 'Streaming on pakutud tulevikusuund, mitte kinnitatud tarnelubadus.']},
{title:'Mida kaasa võtta?',minutes:1,section:'Kontroll ja tootearendus',html:()=>`<h2>Hea tulemus jääb kausta.</h2><p class="quote">Agent teeb töö.<br><span class="em">Projekt säilitab meetodi.</span><br>GIS-ekspert hindab tähendust.</p><div class="source-links"><a href="${REPO}" target="_blank" rel="noopener">OpenMapStacki hoidla ↗</a><a href="https://jaakla.github.io/openmapstack-skills/" target="_blank" rel="noopener">Koduleht ja töötavad näited ↗</a><a href="${PUBLIC_DEMO}" target="_blank" rel="noopener">Tartu sillaanalüüs ja selle päritolu ↗</a></div><p class="caption">Tehnilised allikad: README · project.yaml · pipeline.py · cli.py · validation/latest-report.json. Esitluse alus: autori demokogemus.</p>`,notes:[
 'Kolm mõtet: failipõhine leping, õige ruumiline mõiste, nähtav kontroll.',
 'Installi käsk ja täpne versioon on hoidla README-s. Lingid avanevad eraldi tab’il.']},
{title:'Arutelu: kus oleks teie esimene piloot?',minutes:2,section:'Arutelu',html:()=>`<h2>Kus oleks teie esimene piloot?</h2><div class="discussion"><div><h3>Üks otsus</h3><p>Millist ruumilist küsimust kordate täna käsitsi?</p></div><div><h3>Üks kontroll</h3><p>Milline viga muudaks tulemuse kasutuskõlbmatuks?</p></div><div><h3>Üks piir</h3><p>Millised andmed ja õigused jäävad teie keskkonda?</p></div></div><p class="note-line">Piloodi väljund: sama küsimus, sama mõõdik, nähtav meetod, korratav jooks ja eksperdi hinnang.</p>`,notes:[
 'Võta üks konkreetne pilootnäide. Kui aega vähe, vali ainult kontrollküsimus.',
 'Too arutelu ülesande ja kvaliteedipiiri juurde. 45 minuti lõpp; slaidivalik aitab lisaküsimustega.']}
];
